### ISSUE TITLE
Some <link> tags in the <head> are not getting "Subresource Integrity"

### ISSUE THREAD

**Issue by adamalkrw** [MocioF/No-unsafe-inline#11]
I have subresource integrity enabled but some <link> tags still show up without it, specifically some google fonts links.

There are also some <link> tags which do not have a nonce or subresource integrity, it would seems as if they aren't captured but I did go through the capture process and it doesn't add them as far as I can tell.

My Subresource Integrity settings:
![image](https://github.com/MocioF/No-unsafe-inline/assets/151569271/ebe107f5-bbfa-4c72-9b2d-8e2879085d0c)

Here is an example of a tag which doesn't have the integrity attribute:
![image](https://github.com/MocioF/No-unsafe-inline/assets/151569271/489dd954-ef30-46f3-8844-f32223bc1886)

Here is a list of captured tags related to this problem:
![Capture4567](https://github.com/MocioF/No-unsafe-inline/assets/151569271/165de608-4a50-4332-afaf-3691015ff4c1)
They all say the SHA is generated for them so I would think the SRI should work.

I am using the Divi theme which has built in usage of Google Fonts, perhaps that is related to the issue.

Is there some configuration that I am missing? Or is this some kind of bug?

**Comment by MocioF** [comment]
Google Fonts API does not support Subresource integrity.
Please read here: https://github.com/google/fonts/issues/473

On "No unsafe-inline" we exclude setting SRI for it because the way Google API sends the CSS would always create an error for SRI:
https://github.com/MocioF/No-unsafe-inline/blob/e66be55cd7475f1ea2842441f1f68fb94cde6109/src/Nunil_Manipulate_DOM.php#L955

For regular support requests, please use the WordPress forum.

**Comment by adamalkrw** [comment]
Ah I see, thanks for the quick response. Apologies for not using the forum.
