### ISSUE TITLE
List needed PHP plugins

### ISSUE THREAD

**Issue by mdbraber** [MocioF/No-unsafe-inline#14]
When first trying to load the plugin it would fail with "Unable to load plugin due to fatal error" but no further debug / logs. After some digging I found out I was missing some essential PHP plugins. I think I added the following ot my configuration (PHP8.3) but possibly good to list them somewhere or create an error message that hints at needing these plugins

bcmath
gmp
fileinfo
ctype
mbstring

**Comment by MocioF** [comment]
Hi @mdbraber, it is strange because this function should just do what you ask: print a list of extensions needed. 

https://github.com/MocioF/No-unsafe-inline/blob/92653d48a3a306fd9d030bb191d2f89e72976378/includes/class-no-unsafe-inline-activator.php#L306

It is called at plugin activation, and the activation should stop with an error if requirements aren't met.

https://github.com/MocioF/No-unsafe-inline/blob/92653d48a3a306fd9d030bb191d2f89e72976378/includes/class-no-unsafe-inline-activator.php#L55-L64

Are you asking just to list needed extensions in the readme?

**Comment by mdbraber** [comment]
@MocioF weirdly enough there was no message on plugin activiation on a mention of 'a fatal error' - digging through the code I figured it probably was missing extensions. It would also help probably to add the required extensions in the README indeed.
